//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JordanCity
    {
        public int Id { get; set; }
        public string CitieName { get; set; }
        public double Temp_f { get; set; }
        public double Temp_c { get; set; }
        public System.DateTime Lastupdated { get; set; }
        public System.DateTime Localtime { get; set; }
    }
}
